sudo: false
language: c
compiler:
  - clang
  - gcc
  
env:
    matrix:
      - OS=osx 
      - OS=el DIST=6
      - OS=el DIST=7
      - OS=fedora DIST=23
      - OS=fedora DIST=24
      - OS=fedora DIST=25
      - OS=ubuntu DIST=precise
      - OS=ubuntu DIST=trusty
      - OS=ubuntu DIST=xenial
      - OS=ubuntu DIST=yakkety
      - OS=debian DIST=wheezy
      - OS=debian DIST=jessie
      - OS=debian DIST=stretch
      
before_script:
   - mkdir build
   - cd build
   - cmake ..

script: make     
